# Generated by Django 5.2.16 on 2026-09-17 04:18
#
# 지점에 KPDC 항목 칸 둘을 더한다 (197). 더하기만 하고 자료 이동이 없다 —
# `kpdc_id` 는 `db_default=""` 라 옛 파이프라인 이미지의 INSERT 도 그대로 돈다.
# 그래도 파이프라인 이미지는 같이 굽는다 — `schema_guard`(198)가 장부가 다르면
# 세운다.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0043_taxonname'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='kpdc_id',
            field=models.CharField(blank=True, db_default='', max_length=32),
        ),
        migrations.AddField(
            model_name='locality',
            name='kpdc_meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
