# Generated by Django 5.2.16 on 2026-09-18 09:11
#
# 생층서 기준면 층 (P28). 표 둘(`Biodatum`·`Biozone`)을 새로 만들고
# `Reference` 에 `url` 한 칸을 더한다 — 자료 이동이 없고 더하기만이라
# 파이프라인 이미지를 같이 굽지 않는다(`url` 은 `db_default=""`).
# 행은 `ops/import_biodatums.py` 가 배포 뒤에 넣는다.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0044_locality_kpdc'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='url',
            field=models.CharField(blank=True, db_default='', default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Biozone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=24)),
                ('seq', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('top_ma', models.FloatField(blank=True, null=True)),
                ('base_ma', models.FloatField(blank=True, null=True)),
                ('top_def', models.CharField(blank=True, db_default='', default='', max_length=120)),
                ('base_def', models.CharField(blank=True, db_default='', default='', max_length=120)),
                ('author', models.CharField(blank=True, db_default='', default='', max_length=200)),
            ],
            options={
                'ordering': ['scheme', 'seq'],
                'constraints': [models.UniqueConstraint(fields=('scheme', 'seq'), name='biozone_unique_seq')],
            },
        ),
        migrations.CreateModel(
            name='Biodatum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(blank=True, db_default='', default='', max_length=40)),
                ('seq', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('name_printed', models.CharField(max_length=120)),
                ('binomial', models.CharField(blank=True, db_default='', default='', max_length=120)),
                ('genus', models.CharField(max_length=64)),
                ('infra', models.CharField(blank=True, db_default='', default='', max_length=64)),
                ('datum', models.CharField(choices=[('FO', '최초 산출'), ('LO', '최종 산출'), ('FCO', '흔해지는 층준'), ('LCO', '드물어지는 층준'), ('LCO(LAAD)', '드물어지는 층준 (Cody)'), ('AC1', '극대 1'), ('AC2', '극대 2'), ('AC+LCO', '극대 · 드물어짐')], max_length=12)),
                ('variant', models.CharField(blank=True, db_default='', default='', max_length=24)),
                ('age', models.FloatField()),
                ('age_min', models.FloatField()),
                ('age_max', models.FloatField()),
                ('uncertainty', models.FloatField(blank=True, null=True)),
                ('age_text', models.CharField(blank=True, db_default='', default='', max_length=40)),
                ('zone', models.CharField(blank=True, db_default='', default='', max_length=120)),
                ('code', models.CharField(blank=True, db_default='', default='', max_length=24)),
                ('chron', models.CharField(blank=True, db_default='', default='', max_length=24)),
                ('scheme', models.CharField(blank=True, db_default='', default='', max_length=80)),
                ('timescale', models.CharField(blank=True, db_default='', default='', max_length=80)),
                ('region', models.CharField(blank=True, db_default='', default='', max_length=120)),
                ('confidence', models.CharField(choices=[('high', '원문 대조'), ('recite', '재인용 · 원문 대조'), ('mid', '재인용'), ('low', '웹 요약 1회 · 원문 미대조')], max_length=8)),
                ('primary', models.BooleanField(db_default=False, default=False)),
                ('mis_stated', models.CharField(blank=True, db_default='', default='', max_length=80)),
                ('note', models.TextField(blank=True, db_default='', default='')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biodatums', to='viewer.reference')),
            ],
            options={
                'ordering': ['genus', 'binomial', 'name', 'datum', 'reference_id', 'seq'],
                'indexes': [models.Index(fields=['binomial'], name='viewer_biod_binomia_527b96_idx'), models.Index(fields=['genus'], name='viewer_biod_genus_c39d2e_idx')],
                'constraints': [models.UniqueConstraint(fields=('reference', 'seq'), name='biodatum_unique_seq')],
            },
        ),
    ]
