# Generated by Django 5.2.16 on 2026-09-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0045_biodatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatum',
            name='page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
