# Generated by Django 5.2.16 on 2026-10-02 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0046_biodatum_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absorbed', to='viewer.slide'),
        ),
    ]
